# Generated by Django 5.1.5 on 2025-02-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0004_alter_participante_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
